// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.GameSettings", b =>
                {
                    b.Property<int>("GameSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardWidth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHumanVsComputer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinningCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameSettingsId");

                    b.ToTable("GameSettings");
                });

            modelBuilder.Entity("Domain.SavedGame", b =>
                {
                    b.Property<int>("SavedGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameBoard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GameIsOver")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(32);

                    b.Property<bool>("IsHumanVsComputer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlayerOneMoves")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerOneName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerTwoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("SavedGameId");

                    b.ToTable("SavedGames");
                });
#pragma warning restore 612, 618
        }
    }
}
